### ISSUE TITLE
Add filter for challenges on basis of their running status, category and so on.

### ISSUE THREAD

**Issue by skbly7** [AIcrowd/AIcrowd#1144]
As the number of challenges grows over time, we are having an issue in the challenges list display, in which all the challenges are listed (kind of randomly and need work on ordering now & then).

We need to introduce filters which should be able to help users see challenges based on:
- Running status
- Category/Tags (after https://github.com/AIcrowd/AIcrowd/issues/19)
- Organizers
etc.

**Comment by nemaniarjun** [comment]
The ordering of the challenges is not random and is based on the reorder page that we have. 
We need to implement filter like how we have in the design here: https://aicrowd-design.netlify.com/template-challenges

**Comment by DebalB** [comment]
1. Apart from filters, it would be good to have an "order by" option as well e.g. to see challenges sorted by launch date or end date.
2. Along with the tile view that we have at present, it would be good to have an option for "list view" and "grid view" in order to allow quick glance through of the entries.
3. Would be good to have uniform tile size for all challenges
4. As user keeps clicking on "Load More", the contents add onto same page. As an alternate, multi page option could be explored. This would also give user an indication as to how many further pages are there to browse. Currently this info is missing.
5. There is currently no option to reject the Enable Cookies option.

**Comment by skbly7** [comment]
Being implemented in #1222

**Comment by skbly7** [comment]
Closing this ticket as the original task is completed now after #1222 is merged.
