### ISSUE TITLE
Enable clef_validations in submission.rb file

### ISSUE THREAD

**Issue by piotrekpasciak** [AIcrowd/AIcrowd#1207]
They were disabled quite a while a go for unknown reason.

Things to do to enable validation:
- make sure project setup and seeds work after enabling the validation
- make sure all records pass validation on staging and production - fix records that do not pass it

**Comment by ieggel** [comment]
Hi @piotrekpasciak ,
This was implemented by Sean back in the days (when it was still crowdai.org). If I remember right this was done because as soon as a file is uploaded (to S3), the submission is automatically triggered and somehow validation could not be performed because of this. I do not know why the upload actually triggers a submission, but I remember this being some kind of workaround. Maybe that helps to track down the issue.

**Comment by piotrekpasciak** [comment]
@ieggel 
Main questions is, do we even need these validations?

I wonder, because we have them disabled for 2 years already and noone notice.

**Comment by ieggel** [comment]
Of course it would be good to have them, but yes I agree no one noticed so far;). Would be great if we could get this straight at some point, but it's definitely not high priority.

**Comment by skbly7** [comment]
Removed the dead code from codebase for now, once we have more specific requirements we can enable it properly again.

Should we continue to track it in this issue or @ieggel you would like to open a new issue later when this is needed? Let us know.

**Comment by ieggel** [comment]
@skbly7 let's untrack it. This is really not a priority right now. If needed in the future I will open a new issue . Thanks.

**Comment by skbly7** [comment]
Closed via https://github.com/AIcrowd/AIcrowd/commit/e2da83f15558231ee8404be51fa54530f876b436
