### ISSUE TITLE
Better syntax highlighting in Kramdown

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#399]
_From @spMohanty on November 14, 2017 20:51_

<img width="744" alt="screen shot 2017-11-14 at 21 50 24" src="https://user-images.githubusercontent.com/1581312/32804031-e4664596-c985-11e7-8bb5-50a31a184017.png">

We definitely need to have better syntax highlighting in the forum posts on crowdAI. 

_Copied from original issue: crowdAI/crowdai#424_

**Comment by marcelsalathe** [comment]
I agree. If we're at it, we should also see how we can better distinguish code from links. In the screenshot below, it's hard to see which ones are links and which ones are code style:

<img width="725" alt="screen shot 2017-11-26 at 12 07 59" src="https://user-images.githubusercontent.com/215057/33239457-a713a910-d2a2-11e7-96d4-b6d4136d0814.png">

I'm bringing in @jsnrynlds to help us with this. I'm also removing the low priority label since I think it's actually quite important!

**Comment by marcelsalathe** [comment]
Thanks @jsnrynlds - the first one is better, more neutral. It's also what GitHub uses:
`hello I'm a codeblock`
The only thing I would do is follow GitHub's lead and make the text on the gray background fully black so it truly stands out. It's what millions of developers are used to now.

**Comment by spMohanty** [comment]
Just adding that, apart from this, Kramdown also supports syntax for code blocks in python, ruby, etc, out of the box.
https://kramdown.gettalong.org/syntax_highlighter/rouge.html

@sean : I dont think this is enabled on crowdAI ?
