### ISSUE TITLE
Add the list of all the essential cookies in Privacy Policy

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#813]
The current privacy policy has many `TBC` entries wrt the cookies. 
We need to list down all the cookies used by all the individual components of AIcrowd, and update the Privacy Policy accordingly.

As the site is already live, I would mark it as a high priority task.

**Comment by skbly7** [comment]
Cookies Information for AICrowd.com

| Cookie Name | Source | Owner | Why | More Information |
|--|--|--|--|--|
| _crowdai_session, rack.session | www.aicrowd.com | AICrowd | Essential for user logging & other functionality | - |
| cookie_eu_consented | www.aicrowd.com | AICrowd | To know the browsing user has provided consent | - |
| _ga*, __utm*, _gid, _gcl_au | www.aicrowd.com, .*.cloudfront.net, .cloudflare.com | Google Analytics | Essential for knowing website traffic, engagement for business and scaling decisions | https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage |
| __cf*, _biz* | .cloudflare.com | CloudFlare | Cookie for supporting Cloudflare's security features | https://www.cloudflare.com/cookie-policy/ | https://www.cloudflare.com/cookie-policy/
| _fbp | .cloudflare.com | Facebook | Used by Facebook to deliver a series of advertisement products on Facebook | https://www.facebook.com/about/privacy |
| 1P_JAR | .cloudflare.com | Google | Used by Google to gather website statistics, and track conversion rates | https://policies.google.com/technologies/ads |
| _hp2* | .cloudflare.com | Heap Analytics | Used to track website usage | https://heapanalytics.com/privacy |
| sparrow_id, sparrow_init | .cloudflare.com | Unknown | |

**Comment by skbly7** [comment]
Cookie information for discourse.aicrowd.com (copied from https://meta.discourse.org/t/list-of-cookies-used-by-discourse/83690)


Name | Essential | Expires | Description
-- | -- | -- | --
email | Y | Session | Used during account creation
destination_url | Y | Session | Used during login to redirect to the requested page
sso_destination_url | Y | Session | Used during SSO login to redirect to the requested page
fsl | Y | Session | Full screen login client setting
theme_key | Y | Forever | Client theme personalization. Only used when “Make this my default theme on all my devices” unselected.
cn | Y | Forever | Client clear notifications. I’m counting this as user input instead of personalization because it doesn’t make sense to ‘undo’ or change cleared notifications.
_bypass_cache | Y | Session | Used with ‘fsl’ for full screen login
_t | Y | 1440 hours | User authentication token cookie. SiteSetting.maximum_session_age.hours.from_now
_forum_session | Y | Session | Session cookie
dosp | Y | next page view | Temoporary cookie that informs client denial of service protection is in place.
__profilin | N | Session | Developer only, used by rack-mini-profiler to bypass work
_ga | N | 2 years | Google Analytics cookie.
_gat | N | 2 years | Google Analytics cookie.
_gid | N | 24 hours | Google Analytics cookie.

**Comment by skbly7** [comment]
Cookies Information for gitlab.aicrowd.com

| Cookie Name | Source | Owner | Why | More Information |
|--|--|--|--|--|
| _gitlab_session | gitlab.aicrowd.com | AICrowd | Essential for user logging & other functionality | - |
| sidebar_collapsed | gitlab.aicrowd.com | AICrowd | Required to remember UI setting | - |
| _ga, _gid | .aicrowd.com | Google Analytics | Essential for knowing website traffic, engagement for business and scaling decisions | https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage |
