### ISSUE TITLE
Participant Avatar links are broken on discourse

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#846]
![screen shot 2019-02-26 at 19 36 41](https://user-images.githubusercontent.com/1581312/53437453-dd128b80-39fd-11e9-8afe-a7e2e4a0b5c9.png)

**Comment by skbly7** [comment]
This has been fixed after adding "default image" for users in discourse settings here:
https://discourse.aicrowd.com/admin/site_settings/category/all_results?filter=default%20avatars

Verified with @ffledgling's login.

**Comment by ffledgling** [comment]
@skbly7 I think if the only that was done was to enable "default image", then I'm not quite sure we fixed it. My image was broken because I'd set an image on the aicrowd website and it wasn't showing up on discourse automatically. Did you also do some kind of SSO sync? How do we sync discourse profile pictures with profile pictures from aicrowd?

**Comment by skbly7** [comment]
The images are synced on every new login via SSO. 
Earlier we weren't having avatar being passed from aicrowd.com to discourse.aicrowd.com due to which people who are having quite old sessions haven't get profile picture synced (and hence broken link). 
Once we have default picture in place, it is being rendered as fallback for such cases until they do logout & login or session expires.
