### ISSUE TITLE
User creation workflow is broken

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#906]
@marcelsalathe  's message : 

When I try to sign up with my email xyz@gmail.com, it will just send me back to the sign up page, without an error message
I checked, and the email address is not in our user database
So the problem seems to be with the username - when the username is already taken, the page will not give me an error, and just refuse the account creation.

**Comment by marcelsalathe** [comment]
Update: I confirm that the issue is related to EITHER username OR email address. Thus, if either of those is already taken, sign up fails without an error message.

**Comment by marcelsalathe** [comment]
In addition, there is another bug that needs fixing: when sign up fails, the user is redirected to the signup page, but the "Create Account" button remains inactive, even when all mandatory information is provided. User needs to uncheck and then recheck the first checkbox in order to activate the button.

**Comment by nemaniarjun** [comment]
This was fixed.
