### ISSUE TITLE
Text editor for challenges is completely broken on all browsers

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#979]
none of the buttons do anything

**Comment by nemaniarjun** [comment]
I looked at the code. 
We need to rewrite the whole challenge edit page, properly this time. 
The page code for the editor is hacky at best.

**Comment by spMohanty** [comment]
Lets use a proper markdown editor as soon as we can.
Ex: https://pandao.github.io/editor.md/
or 
https://vuejs.org/v2/examples/
or 
https://simplemde.com/

I will let you guys choose whatever works for us the best.
cc. @piotrekpasciak

**Comment by spMohanty** [comment]
I also quite like these minimalistic editing interfaces : 

https://lab.lepture.com/editor/

**Comment by ieggel** [comment]
@nemaniarjun @spMohanty 
I'm currently creating the new clef challenges and it is virtually impossible to use the current editor. Is it possible that in the meantime you make the editor window bigger at least?
Currently it is so tiny, so in order to edit i always have to write the content somewhere else (e.g. text editor) and the insert back into the AIcrowd editor, which is a bit awkward.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/9192090/72427010-293bfb00-378b-11ea-92dd-71975deb1aef.png)

**Comment by nemaniarjun** [comment]
@ieggel we are aware of this and similar issues on the challenge-edit page, and planning on working on them soon!
Please open new issues if you come across problems that are not on the tracker. 
Thanks!!

**Comment by nemaniarjun** [comment]
@spMohanty @piotrekpasciak https://github.com/sparksuite/simplemde-markdown-editor looks like the best one till now, its a forked improvement of lepture

**Comment by skbly7** [comment]
I am merging the size fix for overview textbox with this issue, because it should be solved after we introduce new editor.

**Comment by piotrekpasciak** [comment]
@nemaniarjun @skbly7 
I've been using CKEditor in previous project and was happy about it:
https://ckeditor.com/

**Comment by nemaniarjun** [comment]
Closing as the basic version is done, going to open a new issue which lists improvements.
